sydney:
  flag: 'images/regions/au.png'
  vms:
    cpu_cost_per_hour: '0.1'
    ram_cost_per_hour: '0.2'
    storage_cost_per_hour: '0.1'
    max_cpu: '10'
    max_ram: '256 GB'
    max_storage: '500 GB'
    flavors:
      s1.micro: '1 GB,1 Core,24 GB'
      s1.small: '2 GB,2 Cores,48 GB'
      s1.medium: '3 GB,4 Cores,96 GB'
      s1.large: '8 GB,6 Cores,192 GB'
chennai:
  flag: 'images/regions/in.png'
  vms:
    cpu_cost_per_hour: '0.15'
    ram_cost_per_hour: '0.22'
    storage_cost_per_hour: '0.22'
    max_cpu: '10'
    max_ram: '128 GB'
    max_storage: '256 GB'
    flavors:
      c1.tmicro: '512 MB,1 Core,10 GB'
      c1.micro: '1 GB,2 Cores,24 GB'
      c1.medium: '2 GB,2 Cores,36 GB'
      c1.large: '3 GB,3 Cores,48 GB'
dar_e_salaam:
  flag: 'images/regions/tz.png'
  vms:
    cpu_cost_per_hour: '0.14'
    ram_cost_per_hour: '0.21'
    storage_cost_per_hour: '0.18'
    max_cpu: '5'
    max_ram: '100 GB'
    max_storage: '1024 GB'
    flavors:
      d1.smicro: '1 GB,2 Core,24 GB'
      d1.msmall: '4 GB,1 Cores,48 GB'
      d1.mmedium: '4 GB,2 Cores,96 GB'
      d1.mlarge: '8 GB,2 Cores,192 GB'
