regions:
  sydney:
    flag: 'images/regions/au.png'
    currency: '&#128;'
    cpu_cost_per_hour: '0.01'
    ram_cost_per_hour: '0.02'
    storage_cost_per_hour: '0.01'
    max_cpu: '10'
    max_ram: '256 GB'
    max_storage: '500 GB'
    flavors:
      s1.micro: '1 GB,1 Core,24 GB'
      s1.small: '2 GB,2 Cores,48 GB'
      s1.medium: '3 GB,4 Cores,96 GB'
    private_ipv4: true
    public_ipv4: false
    private_ipv6: false
    public_ipv6: false

  chennai:
    flag: 'images/regions/in.png'
    currency: '&#8377;'
    cpu_cost_per_hour: '0.009'
    ram_cost_per_hour: '0.019'
    storage_cost_per_hour: '0.019'
    max_cpu: '10'
    max_ram: '128 GB'
    max_storage: '256 GB'
    flavors:
      c1.micro: '1 GB,2 Cores,24 GB'
      c1.medium: '2 GB,2 Cores,36 GB'
      c1.large: '3 GB,3 Cores,48 GB'
    private_ipv4: true
    public_ipv4: true
    private_ipv6: false
    public_ipv6: false

  dar_e_salaam:
    flag: 'images/regions/tz.png'
    currency: 'TZS'
    cpu_cost_per_hour: '0.008'
    ram_cost_per_hour: '0.021'
    storage_cost_per_hour: '0.018'
    max_cpu: '5'
    max_ram: '100 GB'
    max_storage: '1024 GB'
    flavors:
      d1.msmall: '4 GB,1 Cores,48 GB'
      d1.mmedium: '4 GB,2 Cores,96 GB'
      d1.mlarge: '8 GB,2 Cores,192 GB'
    private_ipv4: true
    public_ipv4: false
    private_ipv6: false
    public_ipv6: false
