# Available options:
#
# default   - The default value of the setting.
# client    - Set to true if the javascript should have access to this setting's value.
# refresh   - Set to true if clients should refresh when the setting is changed.
# min       - For a string setting, the minimum length. For an integer setting, the minimum value.
# max       - For a string setting, the maximum length. For an integer setting, the maximum value.
# regex     - A regex that the value must match.
# validator - The name of the class that will be use to validate the value of the setting.
# enum      - The setting has a fixed set of allowed values, and only one can be chosen.
#             Set to the class name that defines the set.
# type: email    - Must be a valid email address.
# type: list     - A list of values, chosen from a set of valid values defined in the choices option.
# type: enum     - A single value, chosen from a set of valid values in the choices option.
#
# A type:list setting with the word 'colors' in its name will make color values have a bold line of the corresponding color
#
required:
  title:
    client: true
    default: 'Vertice'
  site_description:
    default: 'Get a cloud app in 60 seconds'
  contact_email:
    client: true
    default: 'support@megam.io'
    type: email
  contact_url:
    client: true
    default: 'https://www.megam.io'
  notification_email:
    default: 'noreply@unconfigured.megam.io'
    type: email
  disable_customization:
    default: true
  logo_url:
    client: true
    default: '/images/logo_vertice.png'
  logo_small_url:
    client: true
    default: '/images/logo_vertice_small.png'
  logo_reverse_url:
    client: true
    default: '/images/logo_vertice_reverse.png'
  logo_signup_cta:
    client: true
    default: '/images/signup_cta.png'
  signup_cta:
    client: true
    default: "<h3>Launch your applications seamlessly in less than <span>60 seconds</span></h3>"
  favicon_url:
    client: true
    default: '/images/default_favicon.png'
  version_checks:
    default: false
    new_version_emails: false
  prelogin_cta:
    client: true
    default: false
  global_notice:
      default: ""
  minified:
      client: true
      default: false

basic:
  default_locale:
    default: 'en'
    enum: 'LocaleSiteSetting'
    refresh: true
  allow_user_locale:
    default: false
    client: true
  ga_universal_tracking_code:
    client: true
    default: ''
    regex: "^UA-\\d+-\\d+$"
  ga_universal_domain_name:
    client: true
    default: 'auto'
  ga_tracking_code:
    client: true
    default: 'UA-60777472-2'
  ga_domain_name:
    client: true
    default: 'console.megam.io'
  nudgespot_realtimechat_code:
    client: true
    default: '425d0d6f052a5ce5ae21931efa800675'
  left_menu:
    client: true
    type: list
    default: 'dashboard|torpedo|app|service|microservice'
  default_categories:
    client: true
    type: list
    default: 'dashboard|torpedo|app|service|microservice|analytics|collaboration'
  default_categories_muted:
    client: true
    type: list
    default: 'app|service|microservice|collaboration|analytics'

login:
  must_approve_users:
    client: true
    default: false
  enable_local_logins:
    client: true
    default: true
  allow_new_registrations:
    client: true
    default: true
  allow_mobavatar_verifications:
    client: true
    default: false
  infobip_username: ''
  infobip_password: ''
  infobip_api_key: ''
  infobip_application_id: ''
  infobip_message_id: ''
  enable_google_oauth2_logins:
    client: true
    default: false
  google_oauth2_client_id: ''
  google_oauth2_client_secret: ''
  enable_facebook_logins:
    client: true
    default: false
  facebook_app_id:
    default: ''
    regex: "^\\d+$"
  facebook_app_secret:
    default: ''
    regex: "^[a-f0-9]+$"
  enable_github_logins:
    client: true
    default: false
  github_client_id:
    default: 'e9a41xxxxxf3abee2fea'
    regex: "^[a-f0-9]+$"
  github_client_secret:
    default: '3d27d07be2fd36f994xxxxxxxxx15d694cae6'
    regex: "^[a-f0-9]+$"
  oauth_stub_password: "detio"
  enable_sso:
    client: true
    default: false
  enable_sso_provider: false
  sso_url: ''
  sso_secret: ''
  sso_overrides_email: false
  sso_overrides_username: false
  sso_overrides_name: false
  sso_overrides_avatar:
    default: false
    client: true
  sso_not_approved_url: ''
  permanent_session_cookie: true
  enable_ceph_logins:
    client: true
    default: false
  ceph_gateway_timeout:
    client: true
    default: 30
  ceph_gateway: ''
  ceph_username: megdc
  ceph_password: megdc
  email_domains_blacklist:
    default: 'mailinator.com'
    type: list
  email_domains_whitelist:
    default: ''
    type: list

users:
  min_password_length:
    client: true
    default: 8
    min: 1
  block_common_passwords: false
  email_editable: false
  logout_redirect:
    client: true
    default: ''
  full_name_required:
    client: true
    default: false
  invite_expiry_days: 30
  allow_billings:
    client: true
    default: false
  enabled_biller:
    client: true
    default: "WHMCS"
  whmcs_api_url: 'http://192.168.0.120/whmcs/includes/api.php'
  whmcs_username: 'Megam'
  whmcs_password: 'team4megam'
  whmcs_autoauth_url: 'http://192.168.0.120/whmcs/dologin.php'
  whmcs_autoauth_key:  'detAWE123'
  whmcs_clientarea_url:
    client: true
    default: "http://192.168.0.120/whmcs/clientarea.php"
  reserved_emails:
    type: list
    default: "tour@megam.io|test@megam.io|support@megam.io|admin@megam.io"

security:
  use_https: false
  allow_index_in_robots_txt: true
  cors_origins:
    default: ''
    type: list

legal:
  tos_url:
    default: ''
  privacy_policy_url:
    client: true
    default: 'http://www.det.io/privacy'
  faq_url:
    client: true
    default: 'http://docs.det.io/getting_started'
  support_url:
    client: true
    default: 'http://det.megam.io'
  support_email:
    client: true
    default: "support@det.io"
  support_phonenumber:
    client: true
    default: "(02) 7010 1111"

uncategorized:
  version_checks:
    client: true
    default: false
  send_welcome_message: true

  # Search
  min_search_term_length:
    client: true
    default: 3

  max_similar_results: 5

  previous_visit_timeout_hours: 1
