# Available options:
#
# default   - The default value of the setting.
# client    - Set to true if the javascript should have access to this setting's value.
# refresh   - Set to true if clients should refresh when the setting is changed.
# min       - For a string setting, the minimum length. For an integer setting, the minimum value.
# max       - For a string setting, the maximum length. For an integer setting, the maximum value.
# regex     - A regex that the value must match.
# validator - The name of the class that will be use to validate the value of the setting.
# enum      - The setting has a fixed set of allowed values, and only one can be chosen.
#             Set to the class name that defines the set.
# type: email    - Must be a valid email address.
# type: list     - A list of values, chosen from a set of valid values defined in the choices option.
# type: enum     - A single value, chosen from a set of valid values in the choices option.
#
# A type:list setting with the word 'colors' in its name will make color values have a bold line of the corresponding color
#
required:
  title:
    client: true
    default: 'Vertice'
  site_description:
    default: 'One click cloud in 60 seconds'
  contact_email:
    client: true
    default: 'support@megam.io'
    type: email
  contact_url:
    client: true
    default: 'https://www.megam.io'
  notification_email:
    default: 'noreply@unconfigured.megam.io.io'
    type: email
  disable_customization:
    default: true
  logo_url:
    client: true
    default: '/images/logo_vertice.png'
  logo_small_url:
    client: true
    default: '/images/logo_vertice_small.png'
  logo_reverse_url:
    client: true
    default: '/images/logo_vertice_reverse.png'
  favicon_url:
    client: true
    default: '/images/default_favicon.png'
  version_checks:
    default: false
    new_version_emails: false
  global_notice:
      default: ""
  free_wheeling:
      client: true
      default: false

basic:
  default_locale:
    default: 'en'
    enum: 'LocaleSiteSetting'
    refresh: true
  allow_user_locale:
    default: false
    client: true
  ga_universal_tracking_code:
    client: true
    default: ''
    regex: "^UA-\\d+-\\d+$"
  ga_universal_domain_name:
    client: true
    default: 'auto'
  ga_tracking_code:
    client: true
    default: 'UA-60777472-2'
  ga_domain_name:
    client: true
    default: 'console.megam.io'
  nudgespot_realtimechat_code:
    client: true
    default: '425d0d6f052a5ce5ae21931efa800675'
  left_menu:
    client: true
    type: list
    default: 'torpedo|app|service|microservice'
  default_categories:
    client: true
    type: list
    default: 'torpedo|app|service|microservice|analytics|collaboration'
  default_categories_muted:
    client: true
    type: list
    default: 'app|service|microservice|collaboration|analytics'

login:
  must_approve_users:
    client: true
    default: false
  enable_local_logins:
    client: true
    default: true
  allow_new_registrations:
    client: true
    default: true
  allow_otp_verifications:
    client: true
    default: false
  infobip_username: ''
  infobip_password: ''
  infobip_api_key: ''
  infobip_application_id: ''
  infobip_message_id: ''
  enable_google_oauth2_logins:
    client: true
    default: false
  google_oauth2_client_id: ''
  google_oauth2_client_secret: ''
  enable_facebook_logins:
    client: true
    default: false
  facebook_app_id:
    default: ''
    regex: "^\\d+$"
  facebook_app_secret:
    default: ''
    regex: "^[a-f0-9]+$"
  enable_github_logins:
    client: true
    default: true
  github_client_id:
    default: 'e9a41a2be1f3abee2fea'
    regex: "^[a-f0-9]+$"
  github_client_secret:
    default: '3d27d07be2fd36f994b0f0a9c699f315d694cae6'
    regex: "^[a-f0-9]+$"
  enable_sso:
    client: true
    default: false
  enable_sso_provider: false
  sso_url: ''
  sso_secret: ''
  sso_overrides_email: false
  sso_overrides_username: false
  sso_overrides_name: false
  sso_overrides_avatar:
    default: false
    client: true
  sso_not_approved_url: ''
  oauth_stub_password: "detio"
  enable_ceph_logins:
    client: true
    default: false
  ceph_gateway_timeout:
    client: true
    default: 30
  ceph_gateway: ''
  ceph_username: megdc
  ceph_password: megdc
  email_domains_blacklist:
    default: 'mailinator.com'
    type: list
  email_domains_whitelist:
    default: ''
    type: list

users:
  min_password_length:
    client: true
    default: 8
    min: 1
  block_common_passwords: false
  email_editable: false
  logout_redirect:
    client: true
    default: ''
  full_name_required:
    client: true
    default: false
  invite_expiry_days: 30
  allow_default_billings:
    client: true
    default: false
  reserved_emails:
    type: list
    default: "tour@megam.io|test@megam.io|support@megam.io|admin@megam.io"

security:
  use_https: false
  allow_index_in_robots_txt: true
  cors_origins:
    default: ''
    type: list


marketplaces:
  enable_gitlab_source:
    client: true
    default: false
  gitlab_host:
    client: true
    default: 'localhost'

legal:
  tos_url:
    default: ''
  privacy_policy_url:
    default: ''
  faq_url:
    default: 'http://docs.megam.io/docs/megam_oja_gettingstarted'
  support_url:
    default: 'http://support.megam.io'
